version: "3.9"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - landucci-network
  alura-books:
    image: aluradocker/alura-books:1.0
    container_name: alura-books
    networks:
      - landucci-network
    ports:
      - 3000:3000
    depends_on:
      - mongodb
networks:
  landucci-network:
    driver: bridge